service: 
    name: couchbase-api

provider:
  name: aws  
  runtime: nodejs8.10
  role: arn:aws:iam::248113531029:role/lambda-s3-role
  stage: ${opt:stage, 'test'} # Set the default stage used. Default is dev
  region: ${opt:region, 'us-east-1'} # Overwrite the default region used. Default is us-east-1
  stackName: couchbase-api # Use a custom name for the CloudFormation stack
  apiName: Couchbase Management API # Use a custom name for the API Gateway API                
      
functions:
  create:
    handler: handler.create
    events:
      - http:
          path: create
          method: post
  retrieve:
    handler: handler.retrieve
    events:
      - http:
          path: retrieve
          method: get
  update:
    handler: handler.update
    events:
      - http:
          path: update/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: delete
          method: delete