service: gwiz-couchbase-service

provider:
  name: aws  
  runtime: nodejs8.10
  role: arn:aws:iam::248113531029:role/lambda-s3-role
      
functions:
  create:
    handler: handler.create
    events:
      - http:
          path: create
          method: post
  retrieve:
    handler: handler.retrieve
    events:
      - http:
          path: retrieve
          method: get
  update:
    handler: handler.update
    events:
      - http:
          path: update/{id}
          method: put
  delete:
    handler: handler.delete
    events:
      - http:
          path: delete
          method: delete
  fulltextsandbox:
    handler: handler.fulltextsandbox
    events:
      - http:
          path: ftssandbox
          method: get
  dpnamesearch:
    handler: handler.dpnamesearch
    events:
      - http:
          path: dpnamesearch
          method: post
  dpaddresssearch:
    handler: handler.dpaddresssearch
    events:
      - http:
          path: dpaddresssearch
          method: post
